server:
  port: 8081

spring:
  config:
    import: file:.env[.properties]
  application:
    name: history-service
  data:
    mongodb:
      uri: mongodb://${DATA_USERNAME}:${DATA_PASSWORD}@${DATABASE_URL}/${DATABASE_SCHEMA}
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: test-consumer-group