services:
  pg_protobin:
    image: "postgis/postgis:15-3.4"
    container_name: pg_protobin
    environment:
      - "POSTGRES_DB=pg_protobin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_USER=admin"
      - "TZ=UTC"
    ports:
      - "5433:5432"

  kafka_protobin:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_protobin
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

#  redis_protobin:
#    image: "redis:6.0.16"
#    container_name: redis_protobin
#    command: ["redis-server", "--requirepass", "admin"]
#    ports:
#      - "6379:6379"
#  redis-commander-protobin:
#    image: rediscommander/redis-commander:latest
#    restart: always
#    environment:
#      REDIS_HOSTS: redis_protobin
#      REDIS_HOST: redis_protobin
#      REDIS_PORT: 6379
#      REDIS_PASSWORD: admin
#      HTTP_USER: root
#      HTTP_PASSWORD: root
#    ports:
#      - 8081:8081