spring:
  config:
    import: file:.env[.properties]
  application:
    name: protobin
  datasource:
    username: ${DATA_USERNAME}
    password: ${DATA_PASSWORD}
    url: jdbc:postgresql://${DATA_HOST}:${DATA_PORT}/${DATA_NAME}
  liquibase:
    change-log: classpath:db/changelog/master.yml
    enabled: true
    user: ${DATA_USERNAME}
    password: ${DATA_PASSWORD}
    url: jdbc:postgresql://${DATA_HOST}:${DATA_PORT}/${DATA_NAME}
  output:
    ansi:
      enabled: always
springdoc:
  api-docs:
    enabled: true
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  file:
    name: ./logs/project-application.log
  pattern:
    file: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%-5level","thread":"%thread","logger":"%logger{36}","message":"%msg"}%n'
    console: '%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} %msg%n'

history-service-starter:
  kafka-url: localhost:9092